2022-01-26 01:06:07,380 WARN  [main] root: Not connected to any store.
2022-01-26 01:06:10,286 ERROR [main] root: Unknown command.
2022-01-26 01:06:12,691 INFO  [main] root: Application exit.
<<<<<<< HEAD
2022-01-26 23:35:47,216 WARN  [main] root: Not connected to any store.
2022-01-26 23:36:06,612 INFO  [main] root: Connected to localhost on port 8080
2022-01-26 23:36:06,613 INFO  [main] root: Connection established.
2022-01-26 23:36:49,191 INFO  [main] root: Connected to localhost on port 8080
2022-01-26 23:36:49,196 INFO  [main] root: Connection established.
=======
2022-01-26 23:02:36,506 ERROR [main] root: Unknown command.
2022-01-26 23:02:44,720 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:42)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:252)
	at app_kvClient.KVClient.main(KVClient.java:265)
2022-01-26 23:02:44,723 INFO  [main] root: Connection established.
2022-01-26 23:04:32,787 WARN  [main] root: Not connected to any store.
2022-01-26 23:04:40,117 WARN  [main] root: Not connected to any store.
2022-01-26 23:04:43,856 WARN  [main] root: Nothing was connected.
2022-01-26 23:04:48,682 INFO  [main] root: Printed out help.
2022-01-26 23:04:56,701 INFO  [main] root: Log level changed to level DEBUG
2022-01-26 23:05:02,692 INFO  [main] root: Log level changed to level ALL
2022-01-26 23:05:03,652 INFO  [main] root: Application exit.
2022-01-26 23:06:17,373 INFO  [main] root: Application exit.
2022-01-26 23:06:59,228 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:06:59,230 INFO  [main] root: Connection established.
2022-01-26 23:09:15,978 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:09:15,979 INFO  [main] root: Connection established.
2022-01-26 23:12:01,159 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:12:01,160 INFO  [main] root: Connection established.
2022-01-26 23:12:05,891 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:17:56,001 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:17:56,002 INFO  [main] root: Application exit.
2022-01-26 23:18:10,413 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:18:10,414 INFO  [main] root: Connection established.
2022-01-26 23:18:20,490 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:23:24,240 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:23:24,240 INFO  [main] root: Application exit.
2022-01-26 23:23:35,938 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:23:35,939 INFO  [main] root: Connection established.
2022-01-26 23:23:39,006 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:25:10,248 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:25:10,248 INFO  [main] root: Application exit.
2022-01-26 23:25:21,153 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:25:21,154 INFO  [main] root: Connection established.
2022-01-26 23:25:25,450 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:32:11,718 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:32:11,720 INFO  [main] root: Application exit.
2022-01-26 23:32:25,623 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:32:25,624 INFO  [main] root: Connection established.
2022-01-26 23:32:29,891 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:37:51,983 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:37:51,983 INFO  [main] root: Application exit.
<<<<<<< HEAD
2022-01-26 23:57:18,134 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:57:18,135 INFO  [main] root: Connection established.
2022-01-26 23:57:27,283 ERROR [main] root: java.lang.NullPointerException
2022-01-27 00:05:38,037 ERROR [main] root: Unknown command.
2022-01-27 00:12:39,809 INFO  [main] root: Tearing down the connection ...
2022-01-27 00:12:39,810 INFO  [main] root: Application exit.
2022-01-27 00:13:08,152 INFO  [main] root: Connected to localhost on port 8008
2022-01-27 00:13:08,153 INFO  [main] root: Connection established.
2022-01-27 00:13:12,414 ERROR [main] root: java.lang.NullPointerException
2022-01-27 00:14:56,103 INFO  [main] root: Tearing down the connection ...
2022-01-27 00:14:56,103 INFO  [main] root: Application exit.
=======
>>>>>>> 611cf7e6a927926d2ef3533d3e788bbcfbac5bcb
>>>>>>> 3cbdffa0809a779e96dbee603662638d4d4a5f4d
2022-01-27 13:42:58,663 ERROR [main] root: Invalid number of parameters!
2022-01-27 13:43:03,613 ERROR [main] root: Unknown command.
2022-01-27 13:43:08,661 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 13:43:08,661 INFO  [main] root: Connection established.
2022-01-27 13:44:55,616 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:254)
	at app_kvClient.KVClient.main(KVClient.java:267)
2022-01-27 13:44:55,626 INFO  [main] root: Connection established.
2022-01-27 13:45:25,647 ERROR [main] root: Unknown command.
2022-01-27 13:45:36,404 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:46:02,854 ERROR [main] root: Unknown command.
2022-01-27 13:46:05,250 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:46:19,854 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:46:19,854 INFO  [main] root: Disconnected.
2022-01-27 13:46:22,272 ERROR [main] root: Unknown command.
2022-01-27 13:46:27,731 ERROR [main] root: Unknown command.
2022-01-27 13:47:41,607 ERROR [main] root: Unknown command.
2022-01-27 13:47:53,064 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:254)
	at app_kvClient.KVClient.main(KVClient.java:267)
2022-01-27 13:47:53,068 INFO  [main] root: Connection established.
2022-01-27 13:47:57,704 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:49:28,428 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:49:28,431 INFO  [main] root: Connection established.
2022-01-27 13:49:37,321 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:50:47,010 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:258)
	at app_kvClient.KVClient.main(KVClient.java:271)
2022-01-27 13:50:47,019 INFO  [main] root: Connection established.
2022-01-27 13:50:53,127 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:52:41,657 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:52:41,659 INFO  [main] root: Application exit.
2022-01-27 13:52:55,320 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:258)
	at app_kvClient.KVClient.main(KVClient.java:271)
2022-01-27 13:52:55,327 INFO  [main] root: Connection established.
2022-01-27 13:52:58,265 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:53:51,619 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:53:51,620 INFO  [main] root: Application exit.
2022-01-27 13:54:10,401 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:54:10,408 INFO  [main] root: Connection established.
2022-01-27 13:54:13,289 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:55:20,355 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:55:20,355 INFO  [main] root: Application exit.
2022-01-27 13:56:03,628 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:56:03,632 INFO  [main] root: Connection established.
2022-01-27 13:56:06,395 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:57:18,212 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:57:58,297 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:57:58,298 INFO  [main] root: Application exit.
2022-01-27 13:58:33,763 ERROR [main] root: Invalid number of parameters!
2022-01-27 13:58:36,335 ERROR [main] root: Unknown command.
2022-01-27 13:58:42,175 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:58:42,183 INFO  [main] root: Connection established.
2022-01-27 13:58:45,018 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:58:48,805 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:08:16,430 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 14:08:16,442 INFO  [main] root: Connection established.
2022-01-27 14:08:32,442 ERROR [main] root: Unknown command.
2022-01-27 14:08:33,706 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:08:33,706 INFO  [main] root: Application exit.
2022-01-27 14:08:47,233 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:08:47,245 INFO  [main] root: Connection established.
2022-01-27 14:08:51,727 ERROR [main] root: java.io.IOException: Connection is already established
2022-01-27 14:08:56,207 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:09:03,884 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:09:58,157 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:09:58,158 INFO  [main] root: Application exit.
2022-01-27 14:10:40,536 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:10:40,673 INFO  [main] root: Connection established.
2022-01-27 14:10:46,441 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:10:50,476 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:12:58,764 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:12:58,764 INFO  [main] root: Application exit.
2022-01-27 14:13:46,782 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:13:46,816 INFO  [main] root: Connection established.
2022-01-27 14:13:54,941 ERROR [main] root: java.lang.NullPointerException
<<<<<<< HEAD
2022-01-27 14:21:15,053 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:21:15,056 INFO  [main] root: Connection established.
2022-01-27 14:21:55,478 ERROR [main] root: java.io.IOException: Connection is already established
2022-01-27 14:23:29,812 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:23:29,813 INFO  [main] root: Application exit.
=======
2022-01-27 14:25:31,614 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:25:31,615 INFO  [main] root: Connection established.
2022-01-27 14:25:35,997 ERROR [main] root: java.lang.NullPointerException
<<<<<<< HEAD
2022-01-27 14:30:18,791 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:30:18,793 INFO  [main] root: Connection established.
2022-01-27 14:30:21,944 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:31:17,399 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:31:17,405 INFO  [main] root: Connection established.
2022-01-27 14:31:21,051 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:32:05,559 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:32:05,560 INFO  [main] root: Disconnected.
2022-01-27 14:32:07,169 INFO  [main] root: Application exit.
2022-01-27 14:32:38,111 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:32:38,112 INFO  [main] root: Connection established.
2022-01-27 14:32:39,736 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:36:30,516 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:36:30,517 INFO  [main] root: Connection established.
2022-01-27 14:36:32,396 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:37:33,251 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:37:33,252 INFO  [main] root: Connection established.
2022-01-27 14:37:35,363 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:39:02,611 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:39:02,612 INFO  [main] root: Connection established.
2022-01-27 14:39:05,055 ERROR [main] root: java.lang.NullPointerException
=======
>>>>>>> 7bf807522ac88494cbd865158d722872c24db65b
>>>>>>> 9b9b766de0bfdd97d701353f76d6d241e541f662
2022-01-27 14:42:10,567 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:42:10,568 INFO  [main] root: Connection established.
2022-01-27 14:42:13,584 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:46:46,085 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:46:46,086 INFO  [main] root: Connection established.
2022-01-27 14:46:49,701 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:50:16,219 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:50:16,225 INFO  [main] root: Connection established.
2022-01-27 14:50:18,798 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:51:39,225 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:51:39,227 INFO  [main] root: Connection established.
2022-01-27 14:51:41,489 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:53:49,051 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:53:49,052 INFO  [main] root: Connection established.
2022-01-27 14:53:51,938 ERROR [main] root: java.lang.NullPointerException
